### ISSUE TITLE
 Always On Server 1.20.3-unofficial.2-mikkoperkele because it's no longer compatible.

### ISSUE THREAD

**Issue by Hei021** [perkmi/Always-On-Server-for-Multiplayer#2]
Hello,

Just wanted to ask if I am doing something wrong in regards to using the Mod. Thank you very much for your efforts!

**Comment by Hei021** [comment]
Or was it because I am using the old Always On Server.dll? I can't seem to find this file on the edited files so I just copied the old .dll file. Hoping you could assist.

**Comment by Hei021** [comment]
.

**Comment by perkmi** [comment]
Hello, sorry I just saw this because github never sent me an email, are you still having issues?
