### ISSUE TITLE
No DLL?

### ISSUE THREAD

**Issue by sadsandcastle** [perkmi/Always-On-Server-for-Multiplayer#5]
I am not very technical, and I cant seem to run this because every time I try I get a "[SMAPI]       - Always On Server 1.20.3-unofficial.3-mikkoperkele because its DLL 'Always On Server.dll' doesn't exist." error. Using the old Always On Server.dll does not seem to work either.

**Comment by perkmi** [comment]
Are you downloading https://github.com/perkmi/Always-On-Server-for-Multiplayer/releases/download/1.20.3-unofficial.3-mikko_perkele/Always.On.Server.zip then unzipping it and placing the "Always On Server" folder into the "Mods" folder?

**Comment by sadsandcastle** [comment]
I was not downloading from the releases page. Thank you so much for your help. Apologies for having the technical literacy of a 90yr old.

**Comment by perkmi** [comment]
No worries! Glad it's working for you now, maybe I should add some more clear instructions to the readme.
